version: "3"
services:
  server:
    build:
      context: ./server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app

  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/app/src
